# Generated by Django 3.2.10 on 2022-06-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogClubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('teacher', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'blog_clubs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mytable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('name_field', models.TextField(blank=True, db_column='Name', null=True)),
                ('teacher', models.TextField(blank=True, db_column='Teacher', null=True)),
                ('subject', models.TextField(blank=True, db_column='Subject', null=True)),
            ],
            options={
                'db_table': 'mytable',
                'managed': False,
            },
        ),
    ]
