# Generated by Django 3.2.10 on 2022-06-07 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mytable',
            options={'managed': True},
        ),
    ]
