# Generated by Django 3.2.10 on 2022-06-07 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_mytable_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mytable',
            options={'managed': False},
        ),
    ]
