# Generated by Django 3.2.10 on 2022-06-07 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_mytable_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mytable',
            options={'managed': True},
        ),
    ]
