# Generated by Django 3.2.10 on 2022-06-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_mytable_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Olympiads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('date', models.TextField(blank=True, db_column='Date', null=True)),
                ('event', models.TextField(blank=True, db_column='Event', null=True)),
                ('clas', models.TextField(blank=True, db_column='Class', null=True)),
                ('head_teacher', models.TextField(blank=True, db_column='Head-teacher', null=True)),
                ('level', models.TextField(blank=True, db_column='Level', null=True)),
                ('subject', models.TextField(blank=True, db_column='Subject', null=True)),
                ('participants', models.TextField(blank=True, db_column='Participants', null=True)),
                ('result', models.TextField(blank=True, db_column='Result', null=True)),
            ],
            options={
                'db_table': 'olympiads',
                'managed': True,
            },
        ),
        migrations.RenameField(
            model_name='mytable',
            old_name='name_field',
            new_name='name',
        ),
    ]
