# Generated by Django 3.2.10 on 2022-06-09 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220609_1055'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='olympiads',
            table='olympiads.olympiads',
        ),
    ]
