# Generated by Django 3.2.10 on 2022-06-09 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_olympiads_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='olympiads',
            table='olympiads',
        ),
    ]
